# Generated by Django 4.1.3 on 2022-12-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cid',
            new_name='pid',
        ),
    ]
