# Generated by Django 4.1.3 on 2023-01-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
