# Generated by Django 4.1.3 on 2023-01-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vendor_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='Address',
            new_name='address',
        ),
    ]
