# Generated by Django 4.1.3 on 2023-01-31 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='cid',
            new_name='vid',
        ),
    ]
